name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --force

      - name: Build Strapi Project
        run: npm run build

      - name: Deploy via SSH only if build succeeded
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            echo "Stopping old Strapi (if running)..."
            pm2 stop strapi || echo "Strapi not running"

            echo "Cleaning old build..."
            rm -rf /root/test-srapijs-digitalOcean-/*

      - name: Upload Project Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: "."
          target: "/root/test-srapijs-digitalOcean-"

      - name: Restart Strapi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            cd /root/test-srapijs-digitalOcean-
            npm install --force
            pm2 start "npm start" --name "strapi"
